# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jirani/')),
                ('name', models.CharField(max_length=55)),
                ('location', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('health_dpt', models.CharField(max_length=50)),
                ('police_dpt', models.CharField(max_length=50)),
            ],
        ),
    ]
